dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
dotenv: .env
networks:
  default: mainnet-fork
  goerli: 
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
  mainnet-fork: 
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
wallets:
  from_key: ${PRIVATE_KEY}
